### ISSUE TITLE
Report: too high values on the task which was running during the generation

### ISSUE THREAD

**Issue by tuxayo** [mathisdt/trackworktime#25]
Of the two reports I have[1], each one has a crazy high value for the current week on the task which was running during the generation.

Eg.
- 150:25
- 128:47

[1] whose types are
- sums-per-week-last-and-current-month
- sums-per-week-last-and-current-year

**Comment by mathisdt** [comment]
I suspect the report doesn't use the CLOCK_OUT_NOW event which is used in the UI to stop sum calculation at the current time if there is a task running currently.

**Comment by mathisdt** [comment]
@tuxayo Much has happened since, the app is at v1.1.8 currently and has a reworked calculation engine. Could you please check if the error still exists? I'm optimistic that it's fixed now.

**Comment by mathisdt** [comment]
No reaction for a year now, I assume it is fixed and close this issue.

**Comment by tuxayo** [comment]
@mathisdt still happening.
1. start tracking
2. see weekly total, e.g. 40 min
3. reports, current, week, events tomes per task weekly
4. Preview
5. Preview shows 150h instead of 40 min
