### ISSUE TITLE
Report: Not working on oreo

### ISSUE THREAD

**Issue by WildOrangutan** [mathisdt/trackworktime#35]
Reports export has stopped working when my phone was updated to oreo version.

#### Reproduce:

1. Select reports
2. Choose any report type (e.g. "last" + "month")
3. Click any export button (e.g. "all events")
4. Nothing happens

#### Device info:

- Model: LG G6
- Android: 8.0.0

#### Stack trace of error:

```
06-04 08:05:45.442 27503-27503/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.zephyrsoft.trackworktime, PID: 27503
    android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/org.zephyrsoft.trackworktime/files/trackworktime/reports/events-last-month-generated-at-2018-06-04-08-05-45.csv exposed beyond app through ClipData.Item.getUri()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
        at android.net.Uri.checkFileUriExposed(Uri.java:2359)
        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9756)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9762)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9741)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1611)
        at android.app.Activity.startActivityForResult(Activity.java:4479)
        at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
        at android.app.Activity.startActivityForResult(Activity.java:4437)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:856)
        at android.app.Activity.startActivity(Activity.java:4798)
        at android.app.Activity.startActivity(Activity.java:4766)
        at org.zephyrsoft.trackworktime.ReportsActivity$1.onClick(ReportsActivity.java:125)
        at android.view.View.performClick(View.java:6274)
        at android.view.View$PerformClick.run(View.java:24859)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
06-04 08:05:45.442 27503-27503/? E/ACRA: ACRA caught a FileUriExposedException for org.zephyrsoft.trackworktime
    android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/org.zephyrsoft.trackworktime/files/trackworktime/reports/events-last-month-generated-at-2018-06-04-08-05-45.csv exposed beyond app through ClipData.Item.getUri()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
        at android.net.Uri.checkFileUriExposed(Uri.java:2359)
        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9756)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9762)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9741)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1611)
        at android.app.Activity.startActivityForResult(Activity.java:4479)
        at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:48)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
        at android.app.Activity.startActivityForResult(Activity.java:4437)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:856)
        at android.app.Activity.startActivity(Activity.java:4798)
        at android.app.Activity.startActivity(Activity.java:4766)
        at org.zephyrsoft.trackworktime.ReportsActivity$1.onClick(ReportsActivity.java:125)
        at android.view.View.performClick(View.java:6274)
        at android.view.View$PerformClick.run(View.java:24859)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)```

**Comment by tuxayo** [comment]
Duplicate of #32

Which is fixed in master and should be released in 1.0.2 :)

**Comment by mathisdt** [comment]
@WildOrangutan: please check if version 1.0.2 still has this error. As @tuxayo stated it should be fixed.

**Comment by WildOrangutan** [comment]
Wops, sry about duplicate :) will try latest version and report back, if it doesn't work.

**Comment by WildOrangutan** [comment]
Updated to 1.0.2, issue still persists, pretty much same stack trace:

```
06-04 16:53:09.214 14800-14800/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.zephyrsoft.trackworktime, PID: 14800
    android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/org.zephyrsoft.trackworktime/files/trackworktime/reports/events-last-month-generated-at-2018-06-04-16-53-09.csv exposed beyond app through ClipData.Item.getUri()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
        at android.net.Uri.checkFileUriExposed(Uri.java:2359)
        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9756)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9762)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9741)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1611)
        at android.app.Activity.startActivityForResult(Activity.java:4479)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
        at android.app.Activity.startActivityForResult(Activity.java:4437)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
        at android.app.Activity.startActivity(Activity.java:4798)
        at android.app.Activity.startActivity(Activity.java:4766)
        at org.zephyrsoft.trackworktime.ReportsActivity.lambda$onCreate$1$ReportsActivity(ReportsActivity.java:129)
        at org.zephyrsoft.trackworktime.ReportsActivity$$Lambda$1.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6274)
        at android.view.View$PerformClick.run(View.java:24859)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
06-04 16:53:09.215 14800-14800/? E/ACRA: ACRA caught a FileUriExposedException for org.zephyrsoft.trackworktime
    android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/org.zephyrsoft.trackworktime/files/trackworktime/reports/events-last-month-generated-at-2018-06-04-16-53-09.csv exposed beyond app through ClipData.Item.getUri()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
        at android.net.Uri.checkFileUriExposed(Uri.java:2359)
        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9756)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9762)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9741)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1611)
        at android.app.Activity.startActivityForResult(Activity.java:4479)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
        at android.app.Activity.startActivityForResult(Activity.java:4437)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
        at android.app.Activity.startActivity(Activity.java:4798)
        at android.app.Activity.startActivity(Activity.java:4766)
        at org.zephyrsoft.trackworktime.ReportsActivity.lambda$onCreate$1$ReportsActivity(ReportsActivity.java:129)
        at org.zephyrsoft.trackworktime.ReportsActivity$$Lambda$1.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6274)
        at android.view.View$PerformClick.run(View.java:24859)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
06-04 16:53:09.217 14800-14825/? E/trackworktime: ACRA caught a FileUriExposedException for org.zephyrsoft.trackworktime: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/org.zephyrsoft.trackworktime/files/trackworktime/reports/events-last-month-generated-at-2018-06-04-16-53-09.csv exposed beyond app through ClipData.Item.getUri()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
        at android.net.Uri.checkFileUriExposed(Uri.java:2359)
        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9756)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9762)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9741)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1611)
        at android.app.Activity.startActivityForResult(Activity.java:4479)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
        at android.app.Activity.startActivityForResult(Activity.java:4437)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
        at android.app.Activity.startActivity(Activity.java:4798)
        at android.app.Activity.startActivity(Activity.java:4766)
        at org.zephyrsoft.trackworktime.ReportsActivity.lambda$onCreate$1$ReportsActivity(ReportsActivity.java:129)
        at org.zephyrsoft.trackworktime.ReportsActivity$$Lambda$1.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:6274)
        at android.view.View$PerformClick.run(View.java:24859)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6710)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:770)
```
